### ISSUE TITLE
Calling for cats

### ISSUE THREAD

**Issue by leslie-alldridge** [leslie-alldridge/Hacktoberfest-2020-Cats#1]
Looking for users to add some cat pictures to this repository :)

**Comment by hambali999** [comment]
hi im willing to contribute to this for the hacktoberfest! please assign me

**Comment by hidalgo-vntu** [comment]
hi im willing to contribute to this for the hacktoberfest! please assign me

**Comment by leslie-alldridge** [comment]
thanks to everyone for their contributions
